--
-- PostgreSQL database schema for the portfolio website.
--

-- 1. Create the table for storing project information.
CREATE TABLE
  public.profile_websites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    title TEXT NULL,
    url TEXT NULL,
    description TEXT NULL,
    technologies TEXT[] NULL
  );

-- 2. Create the table for managing the list of technologies (for the admin panel dropdown).
CREATE TABLE
  public.technologies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    name TEXT NULL
  );

-- 3. Create the table for tracking page visits.
CREATE TABLE
  public.page_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visited_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ip_address TEXT NULL,
    duration_seconds BIGINT NULL,
    meta JSONB NULL
  );

-- 4. Insert the unique technologies into the 'technologies' table.
INSERT INTO public.technologies (name)
VALUES
  ('Vanilla JS'),
  ('Google Apps Script'),
  ('Supabase'),
  ('Cloudflare Workers'),
  ('Static HTML/CSS'),
  ('PDF.js'),
  ('FFmpeg.wasm');

-- 5. Insert the current project data into the 'profile_websites' table.
-- Note: Descriptions with single quotes are properly escaped by doubling them up ('').
INSERT INTO public.profile_websites (title, url, description, technologies)
VALUES
  (
    'RevealOS Unfilter Tool',
    'https://unfilter.kosherandroid.com/',
    'A powerful tool designed to restore full internet access and app functionality to filtered, kosher-certified phones. It works by safely modifying system partitions, bypassing restrictions without compromising the device''s integrity. It''s a must-have tool for anyone who wants to unlock the full potential of their filtered phone.',
    ARRAY['Vanilla JS']
  ),
  (
    'SK Copilot AI',
    'https://skcopilot.netlify.app/',
    'A user-friendly platform for creating and managing AI-powered GroupMe bots. It allows users to easily configure and deploy bots that can automate tasks, answer questions, and enhance group conversations. It''s the perfect tool for anyone who wants to add a powerful AI assistant to their GroupMe chats.',
    ARRAY['Google Apps Script', 'Supabase']
  ),
  (
    'SKFilter',
    'https://skfilter.netlify.app/',
    'A comprehensive tool for managing and configuring GroupMe group filters. It helps group administrators maintain a safe and positive chat environment by automatically filtering out unwanted content. It''s an essential tool for any GroupMe group administrator.',
    ARRAY['Vanilla JS', 'Supabase']
  ),
  (
    'JTech Website',
    'https://jtechwebsite.shalomkarr.workers.dev/',
    'A reverse mirror proxy for the JTech Forums, providing an alternative way to access the forums and their content. This ensures that the community can always stay connected, even when the main site is unavailable. It''s a great example of how to use Cloudflare Workers to create a simple and effective proxy.',
    ARRAY['Cloudflare Workers']
  ),
  (
    'SK Redirector',
    'https://skredirector.pages.dev/',
    'A convenient browser script that automatically bypasses Techloq filter pages, allowing users to access blocked content without interruption. It''s a simple, effective solution for a smoother browsing experience. It''s a great example of how to use JavaScript to automate tasks and improve the user experience.',
    ARRAY['Vanilla JS']
  ),
  (
    'JTech Redirector',
    'https://jtech-redirector.pages.dev/',
    'A browser script that automatically bypasses filter pages for JTech Forums links, ensuring that users can always access the forums without being blocked. It''s a must-have tool for any active member of the JTech community. It''s a great example of how to use JavaScript to automate tasks and improve the user experience.',
    ARRAY['Vanilla JS']
  ),
  (
    'Rabbi Sacks Website',
    'https://rabbisacks.pages.dev/',
    'A comprehensive website for Rabbi Yonason Sacks, featuring his shiurim, seforim, and community information. It serves as a valuable resource for his students and the wider Jewish community. It''s a great example of how to use web technologies to create a simple and effective website for a community leader.',
    ARRAY['Static HTML/CSS']
  ),
  (
    'The Hock Cleveland',
    'https://thehockcleveland.netlify.app/',
    'A community news platform for Cleveland, providing weekly email blasts and real-time WhatsApp updates. It''s the go-to source for local news, events, and deals, keeping the community connected and informed. It''s a great example of how to use web technologies to create a simple and effective community news platform.',
    ARRAY['Vanilla JS', 'Supabase']
  ),
  (
    'SK Brutes',
    'https://skbrutes.netlify.app/',
    'An educational tool that demonstrates the concept of brute-force password cracking on a simple 4-digit code. It''s a great way to learn about the importance of strong passwords and secure coding practices. It''s a great example of how to use JavaScript to create a simple and effective educational tool.',
    ARRAY['Vanilla JS']
  ),
  (
    'SK Image Fetch',
    'https://skimagefetch.netlify.app/',
    'A powerful tool for creating and managing image retrievers for GroupMe. It allows users to easily find and share images in their GroupMe chats, making conversations more engaging and fun. It''s a great example of how to use JavaScript to create a simple and effective tool for GroupMe.',
    ARRAY['Vanilla JS', 'Supabase']
  ),
  (
    'SK YouTube',
    'https://skyoutube.pages.dev/',
    'A personalized YouTube player that allows users to save and organize their favorite videos. It''s a great way to create a curated collection of content that''s always easy to find and watch. It''s a great example of how to use JavaScript to create a simple and effective tool for YouTube.',
    ARRAY['Vanilla JS', 'Supabase']
  ),
  (
    'Visual PDF Editor',
    'https://fileeditor.netlify.app/',
    'A web-based tool for combining, reordering, and editing pages from PDFs and images. It''s a simple, intuitive solution for managing and manipulating PDF documents without the need for expensive software. It''s a great example of how to use JavaScript to create a simple and effective tool for PDFs.',
    ARRAY['Vanilla JS', 'PDF.js']
  ),
  (
    'Batch WMV to MP4 Converter',
    'https://mp4convert.netlify.app/',
    'A simple web tool for converting multiple WMV files to MP4 format. It''s a fast, efficient solution for anyone who needs to convert video files for use on different devices or platforms. It''s a great example of how to use JavaScript to create a simple and effective tool for video conversion.',
    ARRAY['Vanilla JS', 'FFmpeg.wasm']
  ),
  (
    'Web Media Toolkit',
    'https://mpedit.netlify.app/',
    'A browser-based tool for editing audio metadata and converting media files. It''s a versatile solution for anyone who works with audio or video files on a regular basis. It''s a great example of how to use JavaScript to create a simple and effective tool for media editing.',
    ARRAY['Vanilla JS', 'FFmpeg.wasm']
  ),
  (
    'Kemach',
    'https://kemach.pages.dev/',
    'A Pesach order program for the Kemach community, making it easy for members to order and pay for their Passover essentials. It''s a great example of how technology can be used to support and strengthen local communities. It''s a great example of how to use JavaScript to create a simple and effective tool for community organizing.',
    ARRAY['Vanilla JS', 'Supabase']
  );

-- Blog posts table (if not already created)
CREATE TABLE IF NOT EXISTS
  public.posts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT NULL,
    content_md TEXT NULL,
    tags TEXT[] NULL,
    is_published BOOLEAN NOT NULL DEFAULT false,
    image_url TEXT NULL,
    likes_count BIGINT NOT NULL DEFAULT 0
  );

-- 6. Create the table for tracking post likes.
CREATE TABLE
  public.post_likes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    fingerprint TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(post_id, fingerprint)
  );

-- Enable RLS
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;

-- Allow anonymous reads
CREATE POLICY "Allow public read access" ON public.post_likes FOR SELECT USING (true);

-- Allow anonymous inserts
CREATE POLICY "Allow public insert access" ON public.post_likes FOR INSERT WITH CHECK (true);

-- Allow anonymous deletes (for unlike)
CREATE POLICY "Allow public delete access" ON public.post_likes FOR DELETE USING (true);

-- ============================================
-- Contact Form Messages
-- ============================================
CREATE TABLE IF NOT EXISTS contact_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    is_read BOOLEAN DEFAULT false
);

-- Enable RLS
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (from the public website)
CREATE POLICY "Allow anonymous insert" ON contact_messages
    FOR INSERT
    WITH CHECK (true);

-- Only authenticated users (admin) can read messages
CREATE POLICY "Only admin can read" ON contact_messages
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- Index for admin dashboard queries
CREATE INDEX idx_contact_messages_created_at ON contact_messages(created_at DESC);
CREATE INDEX idx_contact_messages_is_read ON contact_messages(is_read);
