// js/supabase-client.js
// This file was dynamically generated by Cloudflare Pages during the build process.

const SUPABASE_URL = "";
const SUPABASE_ANON_KEY = "";

if (SUPABASE_URL && SUPABASE_URL.startsWith('http')) {
    window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    console.log('Supabase Client Initialized.');
} else {
    console.warn("Supabase Client failed to initialize: Invalid or missing SUPABASE_URL environment variable.");
}