// blog/js/supabase-client.js
// Generated by scripts/inject-env.js at build time — do not edit.

const SUPABASE_URL = "https://qvoxpfigbukidlmshiei.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2b3hwZmlnYnVraWRsbXNoaWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTM2OTEsImV4cCI6MjA2NTg2OTY5MX0.CEbyeIw6QiMxbLBhU7x7Re7SL_unWJMyaJQPS9y-k60";

if (SUPABASE_URL && SUPABASE_URL.startsWith('http')) {
    window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} else {
    console.warn('Supabase Client failed to initialize: invalid or missing SUPABASE_URL.');
}
