// scripts/inject-env.js
//
// Bakes the Supabase config into the two generated files below.
//
// Both values are public: the anon key is served to every visitor in the browser
// bundle, so committing a fallback here loses nothing. The fallback matters because
// a build without SUPABASE_URL / SUPABASE_ANON_KEY in the environment (a local
// `npm run build`, or a Cloudflare Pages build where the vars were scoped to
// Preview only) used to write empty strings into these files — which silently
// broke the sitemap Function and the blog's Supabase client.
//
// If you rotate the project, update FALLBACK_* here.
const fs = require('fs');
const path = require('path');

const FALLBACK_URL = 'https://qvoxpfigbukidlmshiei.supabase.co';
const FALLBACK_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2b3hwZmlnYnVraWRsbXNoaWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTM2OTEsImV4cCI6MjA2NTg2OTY5MX0.CEbyeIw6QiMxbLBhU7x7Re7SL_unWJMyaJQPS9y-k60';

const SUPABASE_URL = process.env.SUPABASE_URL || FALLBACK_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || FALLBACK_ANON_KEY;

const usingEnv = Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY);
console.log(`inject-env: using ${usingEnv ? 'environment variables' : 'committed fallback values'}`);

if (!SUPABASE_URL.startsWith('http') || !SUPABASE_ANON_KEY) {
    console.error('inject-env: refusing to write an empty/invalid Supabase config.');
    process.exit(1);
}

const clientContent = `// blog/js/supabase-client.js
// Generated by scripts/inject-env.js at build time — do not edit.

const SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
const SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};

if (SUPABASE_URL && SUPABASE_URL.startsWith('http')) {
    window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} else {
    console.warn('Supabase Client failed to initialize: invalid or missing SUPABASE_URL.');
}
`;

fs.writeFileSync(path.join(__dirname, '..', 'blog', 'js', 'supabase-client.js'), clientContent, 'utf8');
console.log('inject-env: wrote blog/js/supabase-client.js');

// CF Pages env vars set in the dashboard reach the build step but don't always reach the
// Functions runtime (depends on the scope they were set under). Baking them into a module
// the Function imports sidesteps that — the values get bundled into the deployed Function.
const functionsLibDir = path.join(__dirname, '..', 'functions', '_lib');
fs.mkdirSync(functionsLibDir, { recursive: true });
fs.writeFileSync(
    path.join(functionsLibDir, 'supabase-config.js'),
    `// Generated by scripts/inject-env.js at build time — do not edit.
export const SUPABASE_URL      = ${JSON.stringify(SUPABASE_URL)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
`,
    'utf8'
);
console.log('inject-env: wrote functions/_lib/supabase-config.js');
