// scripts/inject-env.js
const fs = require('fs');
const path = require('path');

const SUPABASE_URL      = process.env.SUPABASE_URL      || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

console.log('Building supabase-client.js with environment variables...');

const clientContent = `
// js/supabase-client.js
// This file was dynamically generated by Cloudflare Pages during the build process.

const SUPABASE_URL = "${SUPABASE_URL}";
const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";

if (SUPABASE_URL && SUPABASE_URL.startsWith('http')) {
    window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    console.log('Supabase Client Initialized.');
} else {
    console.warn("Supabase Client failed to initialize: Invalid or missing SUPABASE_URL environment variable.");
}
`;

const outputPath = path.join(__dirname, '..', 'blog', 'js', 'supabase-client.js');
fs.writeFileSync(outputPath, clientContent.trim(), 'utf8');

console.log('js/supabase-client.js built successfully!');

// ─── Bake the same values into a Pages Functions module ────────────
// CF Pages env vars set in the dashboard reach the build step but
// don't always reach Functions runtime (depends on which "scope"
// they were set under). Writing them into a Function-imported file
// at build time sidesteps that — the values get bundled into the
// deployed Function and are always available via import.
//
// This is safe because both values are public anyway: the anon key
// is exposed in the browser-loaded js/supabase-client.js above.

const functionsLibDir = path.join(__dirname, '..', 'functions', '_lib');
fs.mkdirSync(functionsLibDir, { recursive: true });
const functionConfigPath = path.join(functionsLibDir, 'supabase-config.js');
fs.writeFileSync(
  functionConfigPath,
  `// Auto-generated by scripts/inject-env.js — do not edit.
export const SUPABASE_URL      = ${JSON.stringify(SUPABASE_URL)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
`,
  'utf8'
);
console.log('functions/_lib/supabase-config.js built successfully!');
